
[functions.gestor-trafego-ia]
enabled = true
verify_jwt = true
import_map = "./functions/gestor-trafego-ia/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gestor-trafego-ia/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gestor-trafego-ia/*.html" ]
